### ISSUE TITLE
Release v1.0.6 breaks create_glass if called with list of catalogs

### ISSUE THREAD

**Issue by dominikonysz** [mjhoptics/opticalglass#7]
Loading a Zemax file with `ray-optics` breaks because of the newly added call to `catalog.strip()` before the type-check for strings in version 1.0.6:

```
Traceback (most recent call last):
  File "/Users/dominikonysz/Documents/workspace/optic_env_triplet.py", line 57, in init_optical_system
    base_system = ro.zemax.zmxread.read_lens_file(path)[0]
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/rayoptics/zemax/zmxread.py", line 65, in read_lens_file
    opt_model, info = read_lens(filename, inpt, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/rayoptics/zemax/zmxread.py", line 104, in read_lens
    process_line(opt_model, line, i+1)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/rayoptics/zemax/zmxread.py", line 151, in process_line
    elif _glass_handler(sm, cur, cmd, inputs):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/rayoptics/zemax/zmxread.py", line 547, in __call__
    medium = self.find_glass(name, '')
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/rayoptics/seq/medium.py", line 167, in find_glass
    medium = create_glass(name, catalog)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/opticalglass/glassfactory.py", line 72, in create_glass
    catalog = catalog.strip()
AttributeError: 'list' object has no attribute 'strip'
```

Calling `.strip()` in the calls to `_create_glass(...)` instead seems to be the easiest fix:

```python
  name = name.strip()

  if isinstance(catalog, str):
      return _create_glass(name, catalog.strip())

  else:  # treat catalog as a list
      for cat in catalog:
          try:
              glass = _create_glass(name, cat.strip())
          except ge.GlassError:
              continue
          else:
              return glass
      logging.info('glass %s not found in %s', name, catalog)
      raise ge.GlassNotFoundError(catalog, name)
```

**Comment by mjhoptics** [comment]
Hello @dominikonysz,
Thank you for the report and suggested fix. I updated your changes and some additional tests and there should be a new v1.0.7 available on pypi and conda (soon, for the latter).
Thank again for your help.
Mike Hayford
